# DATABASE
server:
  port: 8234

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl_exam?useUnicode=true&characterEncoding=utf8&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sbsst
    password: sbs123414
  # JPA
  jpa:
    hibernate:
      ddl-auto: create
  # CONSOLE
  output:
    ansi:
      enabled: always